<?php
if (!defined("ABSPATH")) { return; }

/*
* Auto-generated by Nexter Code Snippets.
* DO NOT EDIT THIS FILE MANUALLY.
*/
return array (
  'publish' => 
  array (
    '1-disable-emojis-for-faster.php' => 
    array (
      'name' => 'Disable Emojis for Faster Loading',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Performance',
        1 => 'Optimization',
        2 => 'Frontend',
      ),
      'description' => 'Disable WordPress emoji scripts to improve page speed.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'front-end',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-02-26 13:35:41',
      'created_at' => '2026-02-26 13:35:41',
      'file_name' => '1-disable-emojis-for-faster.php',
    ),
    '2-add-google-analytics-tracking.php' => 
    array (
      'name' => 'Add Google Analytics Tracking Code',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Analytics',
        1 => 'Tracking',
        2 => 'Frontend',
      ),
      'description' => 'Insert Google Analytics script directly without extra plugins.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'front-end',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-02-26 13:35:41',
      'created_at' => '2026-02-26 13:35:41',
      'file_name' => '2-add-google-analytics-tracking.php',
    ),
    '3-limit-post-revisions-to.php' => 
    array (
      'name' => 'Limit Post Revisions to Optimize Database',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Database',
        1 => 'Optimization',
        2 => 'Performance',
      ),
      'description' => 'Restrict number of saved post revisions to reduce database size.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'global',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-02-26 13:35:41',
      'created_at' => '2026-02-26 13:35:41',
      'file_name' => '3-limit-post-revisions-to.php',
    ),
    '4-customize-login-logo-link.php' => 
    array (
      'name' => 'Customize Login Logo Link URL',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Branding',
        1 => 'Login-Page',
        2 => 'Frontend',
      ),
      'description' => 'Change WordPress login logo URL to your site homepage.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'front-end',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-02-26 13:35:41',
      'created_at' => '2026-02-26 13:35:41',
      'file_name' => '4-customize-login-logo-link.php',
    ),
    '5-disable-gutenberg-editor-use.php' => 
    array (
      'name' => 'Disable Gutenberg Editor (Use Classic Editor)',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Editor',
        1 => 'Backend',
        2 => 'Classic',
      ),
      'description' => 'Disable Gutenberg block editor and enable classic editor experience.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'front-end',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-02-26 13:35:41',
      'created_at' => '2026-02-26 13:35:41',
      'file_name' => '5-disable-gutenberg-editor-use.php',
    ),
  ),
  'draft' => 
  array (
  ),
  'meta' => 
  array (
    'secret_key' => '95791f47c33796518737d35a30c814a8',
    'now_date' => '2026-02-26 13:35:41',
    'version' => '4.5.3',
    'domain' => 'https://skylarkapparelltd.com',
  ),
  'error_files' => 
  array (
  ),
);